server:
  host: "localhost"
  port: 8080

database:
  host: "localhost"
  port: 5433
  name: "postgres"
  user: "root"
  password: "pass"
  database: "netflix-rental"

email:
  host: "smtp.gmail.com"
  port: "587"
  from: "test2022pratibha@gmail.com"
  password: "tpqd dacb wtkd mjpx"
